name: Release on Script Change

permissions:
  contents: write
  actions: read

on:
  push:
    paths: # Runs on changes in specific files
      - Install-NvidiaApp.ps1
      - README.md
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Version to Today's Date
        id: extract_version
        run: |
          $version = (Get-Date -Format "yy.MM.dd")
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Upload Install-NvidiaApp.ps1
        uses: actions/upload-artifact@v4
        with:
          name: install-nvidiaapp-ps1
          path: ./Install-NvidiaApp.ps1

      - name: Upload README.md
        uses: actions/upload-artifact@v4
        with:
          name: readme-md
          path: ./README.md

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Install-NvidiaApp.ps1
        uses: actions/download-artifact@v4
        with:
          name: install-nvidiaapp-ps1
          path: ./output

      - name: Download README.md
        uses: actions/download-artifact@v4
        with:
          name: readme-md
          path: ./output

      - name: Set Version to Today's Date
        id: extract_version
        run: |
          $version = (Get-Date -Format "yy.MM.dd")
          echo "VERSION=$version" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Dry Run of Install-NvidiaApp.ps1
        run: pwsh -Command "./output/Install-NvidiaApp.ps1 -DryRun -Force"

      - name: Read README.md
        id: read_readme
        run: |
          $readme = Get-Content -Path ./output/README.md -Raw
          echo "README_CONTENT<<EOF" >> $env:GITHUB_ENV
          echo "$readme" >> $env:GITHUB_ENV
          echo "EOF" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Install-NvidiaApp.ps1 Release ${{ env.VERSION }}"
          body: ${{ env.README_CONTENT }}
          files: |
            ./output/Install-NvidiaApp.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}